DETERMINISTIC_PIPELINE = [
    'SOURCE UPLOAD','DATA ANALYZER','RAW EVIDENCE VAULT','NORMALIZATION ENGINE',
    'MASTER ACTIVITY ENGINE','WBS / CODING ENGINE','ENGINEERING READINESS ENGINE',
    'PROCUREMENT ENGINE','PRODUCTIVITY ENGINE','CREW ENGINE','EQUIPMENT ENGINE',
    'MATERIAL ENGINE','QUANTITY + BASE-TIME ENGINE','DURATION / MAN-HOUR ENGINE',
    'CONSTRUCTION SEQUENCING ENGINE','MEP STAGE ENGINE','AACE 38R-06 SCHEDULE BASIS ENGINE',
    'AACE 48R-06 CONSTRUCTABILITY ENGINE','SCHEDULE QA / CONFLICT GATE',
    'USER / ENGINEER DECISION GATE','PRIMAVERA SCHEDULE BUILDER','XER VALIDATION',
    'XER CREATOR','PRIMAVERA P6 NATIVE IMPORT','P6 NATIVE CPM CALCULATION',
    'POST-P6 QA','FINAL OUTPUTS'
]

ML_ENHANCED_PIPELINE = [
    'SOURCE FILES','DATA ANALYZER','RAW EVIDENCE VAULT','NORMALIZATION','MASTER ACTIVITY ENGINE',
    'ML ACTIVITY CLASSIFICATION','ENGINEERING ENGINE','ML ENGINEERING-RISK PREDICTION',
    'PROCUREMENT ENGINE','ML PROCUREMENT-RISK PREDICTION','PRODUCTIVITY ENGINE',
    'ML PRODUCTIVITY PREDICTION','CREW ENGINE','ML CREW RECOMMENDATION','EQUIPMENT ENGINE',
    'MATERIAL ENGINE','QUANTITY / BASE-TIME ENGINE','DETERMINISTIC DURATION ENGINE',
    'ML DURATION-RISK ENGINE','CONSTRUCTION SEQUENCE ENGINE','ML LOGIC SUGGESTION',
    'AACE 38R-06','AACE 48R-06','ML CONSTRUCTABILITY-RISK ENGINE','SCHEDULE QA',
    'ML ANOMALY DETECTION','ENGINEER DECISION','PRIMAVERA SCHEDULE MODEL','XER VALIDATION',
    'XER CREATOR','P6 NATIVE CPM','POST-P6 QA','ACTUAL PROJECT RESULTS',
    'CONTROLLED MACHINE LEARNING LOOP'
]

def pipeline_definition():
    return {
        'golden_rule': ['PRESERVE','NORMALIZE','ANALYZE','ENGINEER','CALCULATE','REVIEW','APPROVE','EXPORT'],
        'deterministic_pipeline': [{'order':i+1,'stage':s} for i,s in enumerate(DETERMINISTIC_PIPELINE)],
        'ml_enhanced_pipeline': [{'order':i+1,'stage':s} for i,s in enumerate(ML_ENHANCED_PIPELINE)],
        'p6_authority': 'Native Primavera P6 remains authoritative for CPM dates, float, longest path, calendar/constraint effects and resource leveling after XER import.',
        'missing_value_policy': ['MISSING','UNKNOWN','UNRESOLVED','REVIEW_REQUIRED'],
    }
